### ISSUE TITLE
arm64 install with --enable-optimization error

### ISSUE THREAD

**Issue by geometry88** [colesbury/nogil#105]
/bin/sh: line 9: 3051353 Segmentation fault      (core dumped) CC='gcc -pthread'                                                                                                                                                              LDSHARED='gcc -pthread -shared    -fprofile-generate' OPT='-DNDEBUG -g -fwrapv                                                                                                                                                              -O3 -Wall' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python -E ./setup.py $quiet build
make[3]: *** [Makefile:661: sharedmods] Error 139
make[3]: Leaving directory '/root/nogil'
make[2]: *** [Makefile:554: build_all_generate_profile] Error 2
make[2]: Leaving directory '/root/nogil'
make[1]: *** [Makefile:530: profile-gen-stamp] Error 2
make[1]: Leaving directory '/root/nogil'
make: *** [Makefile:542: profile-run-stamp] Error 2

there are no errors without this flag

![image](https://user-images.githubusercontent.com/16748478/216845445-9bfa86a0-0c25-494d-83ca-5e70848dc69e.png)

**Comment by colesbury** [comment]
Thanks for the bug report. This is fixed now.
