### ISSUE TITLE
can't import apose.email , KeyError raised

### ISSUE THREAD

**Issue by dc3l1ne** [colesbury/nogil#108]
Hello colesbury !
Thanks for your working ! It really helps me a lot . But it seems that some packages cannot be loaded on this version.
I install this package via `pip install Aspose.Email-for-Python-via-NET` , but when I use `from apose.email import MailMessage` or `import apose.email` , python will raise KeyError.
I tried build python in Ubuntu 18.04 and Ubuntu 22.04 , and all modules were built successfully unless _decimal.
Hope I can get your answer !

**Comment by colesbury** [comment]
Hi @dc3l1ne, thanks for the bug report. Sorry this fell of my radar. I'll look into it tomorrow.

**Comment by colesbury** [comment]
Sorry, I don't think it's possible to support `Aspose.Email-for-Python-via-NET`. The package contains binary libraries for specific versions of Python. It's not possible for me to re-compile those for "nogil" Python because the package is not open source.

**Comment by dc3l1ne** [comment]
Thanks for the reply. I thought it was the python which caused it , and according to your answer, I think it's impossible to fix it with a compiled package.

**Comment by colesbury** [comment]
Yeah, as far as I can tell, it's only possible for the author of the Apose package to fix (by recompiling for nogil Python.) You can try asking on their support page.
