### ISSUE TITLE
Is it possible to use multithreaded feature without GIL in Jupyter notebook?

### ISSUE THREAD

**Issue by Vitalic57** [colesbury/nogil#112]
Hello! 

I have tried this script in Jupyter notebook, performance is worse than in one thread scenario multiplied by number of threads in this scenario. 

```
import sys
from concurrent.futures import ThreadPoolExecutor

print(f"nogil={getattr(sys.flags, 'nogil', False)}")

def fib(n):
    if n < 2: return 1
    return fib(n-1) + fib(n-2)

threads = 8

with ThreadPoolExecutor(max_workers=threads) as executor:
    for _ in range(threads):
        executor.submit(lambda: print(fib(34)))
```

**Comment by colesbury** [comment]
I think the way that Jupyter notebooks define functions in cells can lead to a lot of reference count contention in the current implementation. It should be fixable, but I'd recommend not using Jupyter notebooks if you want multithreaded scaling for now.

**Comment by Vitalic57** [comment]
Ok, thanks for the answer.
