### ISSUE TITLE
error with rust pyo3

### ISSUE THREAD

**Issue by zqqqqz2000** [colesbury/nogil#115]
getting this error:
```
python: Objects/moduleobject.c:46: PyModuleDef_Init: Assertion `_PyObject_IS_IMMORTAL((PyObject*) def)' failed.
[1]    525211 IOT instruction (core dumped)  python
```
this is my code in rust, it just declare a module and do nothing:
```
use pyo3::prelude::*;

#[pymodule]
fn test_pyo3(_py: Python<'_>, m: &PyModule) -> PyResult<()> {
    Ok(())
}
```
in python:
```
import test_pyo3
```
looks like pyo3 return an immortal object with refcount 0 ? according to
https://github.com/colesbury/nogil/blob/nogil/Include/object.h#L486.
but it works fine in other python version.

**Comment by zqqqqz2000** [comment]
@colesbury hello? need a bit help here~ thx

**Comment by colesbury** [comment]
Hi @zqqqqz2000, sorry for the slow response. I've been on vacation the past few weeks.

pyo3 needs modifications to work correctly with nogil. I have a work-in-progress branch here: https://github.com/colesbury/pyo3/tree/0.15.2-nogil, but it doesn't address all the thread-safety issues. There's discussion about how to properly address the issues over at the pyo3 issue tracker, but I'm waiting until a decision on PEP 703 before further pursuing that.

**Comment by zqqqqz2000** [comment]
got it, thx!
