### ISSUE TITLE
Nogil PyTorch threading issue when subclassing Tensor

### ISSUE THREAD

**Issue by bridgesign** [colesbury/nogil#120]
Installing pytorch using pip in the docker raises the following when multiple threads are being used.

```SystemError: <Method 'clone' of 'torch._C._TensorBase' objects> returned null without setting an error```

The error is coming for all torch operations, with or without GPU. When PYTHONGIL=1 is set, then it seems to work.

I also tried to compile the wheel just to ensure if it is any other issue, but it seems like the build is broken with the new nogil version.

Any idea how it can be solved? I tried to get the CPP traces but setting the TORCH_SHOW_CPP_STACKTRACES=1 did not work.

**Comment by colesbury** [comment]
Hi @bridgesign, thanks for the bug report. Would you please provide some more details:
1) What operating system are you using?
2) Which version of PyTorch?
3) Would you please provide some sample code to reproduce the issue?

**Comment by bridgesign** [comment]
Hi @colesbury,

I did some testing and found that the bug specifically comes when `torch.Tensor` is subclassed. Changed the issue topic to reflect that.

1. I tested it on Windows WSL (docker-desktop) and Linux Ubuntu 20.04 amd64 machine (kubernetes) using the nogil/python image.
2. Used direct pip install. The version via pip is 1.9.0
3. Below is the minimum reproducible code

```
import threading as th
import torch

# Error occurs when using a custom tensor class
class mt(torch.Tensor): pass

def thread_func():
    # Do multiple times to increase chance of error
    for _ in range(100):
        position = torch.tensor((0.0, 0.0)).as_subclass(mt)
        landmark = torch.tensor((3.0, 4.0)).as_subclass(mt)
        landmark + position

if __name__ == '__main__':
    # Create threads
    threads = []
    # Creates error when using more than 1 thread
    for i in range(2):
        threads.append(th.Thread(target=thread_func))
    # Start threads
    for thread in threads:
        thread.start()
    # Join threads
    for thread in threads:
        thread.join()
```

The issue only comes when the following conditions are true:
1. Multiple cores execute the code
2. Tensor is subclassed

Stack Trace:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 935, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 886, in run
    self._target(*self._args, **self._kwargs)
  File "/src/test_thread.py", line 12, in thread_func
    landmark + position
SystemError: <method '__add__' of 'torch._C._TensorBase' objects> returned NULL without setting an error
```

Hope this answers all the questions.

**Comment by colesbury** [comment]
Thanks, I'm able to reproduce the issue now.

**Comment by colesbury** [comment]
Hi @bridgesign, I've uploaded a new version of PyTorch 1.9.0 for Linux that fixes this issue.

I haven't fixed the macOS wheels yet.
