### ISSUE TITLE
wheel for zstandard (fix for nogil)

### ISSUE THREAD

**Issue by jimkring** [colesbury/nogil#124]
hi @colesbury.

I’m excited to see things moving ahead :)

I was doing some testing and ran into some issues installing zstandard on nogil. I’ve made a (hopefully sane/minor) fix and submitted a PR: https://github.com/indygreg/python-zstandard/pull/201

it would be nice to have a wheel built for nogil available in pip.  Alternatively, I can pip install it from my fork:

`pip install git+https://github.com/jimkring/python-zstandard-nogil@main`

cheers,

**Comment by colesbury** [comment]
Wheels are built https://d1yxz45j0ypngg.cloudfront.net/zstandard/
