### ISSUE TITLE
Uploading this python version to aws layer

### ISSUE THREAD

**Issue by marchostau** [colesbury/nogil#128]
Anyone have ever upload this python version to aws layer in order to execute code in AWS Lambda using this python interpreter? 
1. I'm having problems in the size of the interpreter (I want to upload /home/user/pyenv/versions/nogil-3.1.10-1 with all the directories: bin, include, lib and share. I've upload this zip to S3 but the layer only allows me to use 0.262 GB and the unzipped directory occupy 0,326GB). 
2. I'm also having problems with the dynamic dependencies of the python interpreter (ldd python) that I think can cause problems when I will try to use the python interpreter inside an AWS Lambda (I've installed the python interpreter in an EC2 instance with amazonlinux OS to reduce compatibility problems). I add an image so you can see the dependencies.
![1](https://github.com/colesbury/nogil/assets/82412218/bb38d749-3efb-4914-9834-b1f99e9ebd19)

**Comment by colesbury** [comment]
If you want a installation that you can just unzip, use the `python-3.9.10-nogil-linux.tar.gz` file from https://github.com/colesbury/nogil/releases/tag/v3.9.10-nogil-2023-04-01.

Why are you using this with AWS lambda?

**Comment by marchostau** [comment]
I'm trying to research how good can be multithreading vs the use of pipes (multiprocessing doesn't work). If I do what you tell I Will haver the same problems with the dynamic linkage of libraries associated to Python. Haver you ever tried using this on aws lambda?

**Comment by colesbury** [comment]
I have never used AWS lambda. The pyenv installations are not not relocatable -- you can't just move them from one directory to another (nor one machine to another). The released ZIP files are designed to relocatable. You should be able to just extract the ZIP and run it.

I'm surprised by the combination of this project and AWS lambda as the number of vCPUs for lambda is quite limited, and from what I understand, tied to the amount of memory allocated to a lambda function.

**Comment by marchostau** [comment]
But before passing the Zip to the layer I've to built the interpreter from source (Git clone, ./configure, Make, Make install) and zip the nogil completely (if i don't built It i can't use the executable Python file). The Python binary inside the directory has dynamic dependencies as the image. Once I upload this zip to the layer, the aws lambda will give me problems related to this dependencies (i tried to add the dependencies to the zip but It doesn't work, the OS detects It).

**Comment by marchostau** [comment]
I've solved the problem. You can deploy aws lambda function from a docker container. Thank you!
