### ISSUE TITLE
an error occured when building the msi files

### ISSUE THREAD

**Issue by Hacid** [colesbury/nogil#132]
![联想截图_20231209094214](https://github.com/colesbury/nogil/assets/23780869/1104ae3b-e990-4738-921a-990c25a2a6f9)
like this,using environmrnt is MSBuild2017 in windows x64,and my cmd command:buildrelease.bat -x64 -o D:\python\nogil-nogil\PCbuild

**Comment by colesbury** [comment]
Use the builds from https://github.com/colesbury/nogil/releases

**Comment by colesbury** [comment]
See https://github.com/colesbury/nogil/blob/nogil/.github/workflows/windows.yml for how the releases are built. The `buildrelease.bat` script does not work. The releases use `Tools\msi\buildnogil.bat -x64`.
