### ISSUE TITLE
Can't install nogil on MacOS. (arm64)

### ISSUE THREAD

**Issue by LittleBread69** [colesbury/nogil#135]
SPECS:
Macbook Pro M1 13 in.
8Gb Ram
512 Gb SSD

I tried to install nogil by using pyenv but it threw me an error: 

`
pyenv install nogil-3.9.10-1
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading nogil-3.9.10-1.tar.gz...
-> https://github.com/colesbury/nogil/archive/refs/tags/v3.9.10-nogil-2023-01-22.tar.gz
Installing nogil-3.9.10-1...

BUILD FAILED (OS X 14.3 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/93/q432xvq53px49vw7_r1b0ql00000gn/T/python-build.20240204171510.75007
Results logged to /var/folders/93/q432xvq53px49vw7_r1b0ql00000gn/T/python-build.20240204171510.75007.log

Last 10 log lines:
      _PyLocale_localeconv in libpython3.9.a[156](_localemodule.o)
      _PyLocale_localeconv in libpython3.9.a[156](_localemodule.o)
      _PyLocale_localeconv in libpython3.9.a[156](_localemodule.o)
  _libintl_textdomain, referenced from:
      _PyIntl_textdomain in libpython3.9.a[156](_localemodule.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python.exe] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Programs/_testembed] Error 1
`

I also tried to build from source and it didn't work.
I tried to `brew update` but it didn't change anything.

**Comment by colesbury** [comment]
This looks like https://github.com/pyenv/pyenv/issues/1877#issuecomment-836115970. There's a number suggested workarounds there, can you try them?

**Comment by albanie** [comment]
I had the same issue as @LittleBread69 above. 
Using the solution linked above by @colesbury worked for me.

### My scenario

Hardware: 2023 MacBook pro (M2 Max)
OS: Sonoma 14.3
Pyenv version: 2.3.20
Homebrew version: 4.2.5

### Solution

The specific command I ran (based on the link above):
`export LDFLAGS="-L/opt/homebrew/lib"; export CPPFLAGS="-I/opt/homebrew/include" ; pyenv install nogil-3.9.10-1`

### Validation

To check it's working:
```
pyenv local nogil-3.9.10-1
python3 -c "import sys; print(sys.flags.nogil)"
# Outputs "True"
```

**Comment by LittleBread69** [comment]
It worked and now it's fixed. Thank you a lot.
