### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by xbit18** [colesbury/nogil#136]
Hello, first time ever proposing something on Github. 

**Problem:**
Through experimentation I found that the docker method doesn't work for arm64 (Macbook Air M1 in particular). 

**Solution:**
I found that by changing the first line of the Dockerfile, which is:
"FROM buildpack-deps:bullseye"
to this:
"FROM arm64v8/buildpack-deps:bullseye", the image then supports the arm64 architecture.

After building this local image, it can be used instead of the standard nogil/python that's on dockerhub.

It would be nice to publish this version too on dockerhub, maybe with a name like "nogil/pythonarm" to be more easily used.
Those are my two cents, thanks!

**Comment by colesbury** [comment]
Hi @xbit18, my current focus is on getting the nogil changes upstreamed into the upcoming CPython 3.13 release, so I don't think I'll have time to add a Docker image for macOS arm64. I'd be happy to review a PR, though.

**Comment by xbit18** [comment]
Hey @colesbury thanks for the quick reply!
Yes, I'm following your work and actually writing a thesis on the subject :)
I'd happily do a PR but what would I do? Perhaps I can add another Dockerfile for building this new image. It's my first contribution to an open source project so I'm sorry for the trouble of explaining this trivial stuff.

**Comment by xbit18** [comment]
@colesbury nevermind, I looked at your workflows setup, I think I know what to do
