### ISSUE TITLE
Not getting numpy

### ISSUE THREAD

**Issue by smontanaro** [colesbury/nogil#25]
In a [now-closed issue](https://github.com/colesbury/nogil/issues/23) Sam wrote:

> The "nogil" branch pulls the patched NumPy wheel (it contains a modified "pip" that pulls from https://d1yxz45j0ypngg.cloudfront.net/).

I built from the nogil branch (not nogil-3.9), ran ensure pip to get the modified pip, then tried to install numpy.

Looking at the pip-ish bits included in the nogil branch, it seems to have two versions of pip, 19.2.3 and 21.2.4:

```
(python39) nogil% find . -name '*pip*' '*pip*'
...
./Lib/ensurepip
./Lib/ensurepip/_bundled/pip-19.2.3-py2.py3-none-any.whl
./Lib/ensurepip/_bundled/pip-21.2.4-py3-none-any.whl
...
```

Ensure-pip installed the 21.2.4 version:

```
(python39) nogil% ./python -m pip --version
pip 21.2.4 from /home/skip/.local/lib/python3.9/site-packages/pip (python 3.9)
```

When I tried to install numpy I was rebuffed:

```
% ./python -m pip --verbose install numpy 
Using pip 21.2.4 from /home/skip/.local/lib/python3.9/site-packages/pip (python 3.9)
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local/include/python3.9d/UNKNOWN
sysconfig: /home/skip/src/python/nogil/Include/UNKNOWN
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://d1yxz45j0ypngg.cloudfront.net/, https://pypi.org/simple
ERROR: Could not find a version that satisfies the requirement numpy (from versions: none)
ERROR: No matching distribution found for numpy
WARNING: You are using pip version 21.2.4; however, version 21.3 is available.
You should consider upgrading via the '/home/skip/src/python/nogil/python -m pip install --upgrade pip' command.
```

Looking on the cloudfront.net index for [numpy](https://d1yxz45j0ypngg.cloudfront.net/numpy/) I saw two wheels:

```
numpy-1.19.3-nogil39-nogil_39_x86_64_linux_gnu-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
numpy-1.19.4-nogil39-nogil_39_x86_64_linux_gnu-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

Why wasn't one of them installed? I'm running on an XUbuntu 20.04 system. I wasn't able to (with my feeble pip-fu) coax pip into emitting more information about the requirements it was looking for.

**Comment by Red-Eyed** [comment]
Everything works fine at my side. 

### My system:
```bash
OS: Ubuntu 20.04.3 LTS on Windows 10 x86_64        
Kernel: 5.10.60.1-microsoft-standard-WSL2          
Uptime: 3 hours, 26 mins                           
Packages: 1603 (dpkg)                              
Shell: bash 5.0.17                                 
Theme: Adwaita [GTK3]                              
Icons: Adwaita [GTK3]                              
Terminal: /dev/pts/0                               
CPU: Intel i7-9800X (16) @ 3.791GHz                
GPU: 1d02:00:00.0 Microsoft Corporation Device 008e
Memory: 309MiB / 15844MiB                          
```

## Python building:
```bash
sudo apt install libssl-dev
git clone https://github.com/colesbury/nogil.git
cd nogil
unset ${!PYTHON@}
./configure --with-ensurepip=install --prefix=$PWD/nogil_build
make -j
make install
cd nogil_build
./bin/python3 -m pip install  numpy ipython
./bin/python3 -m IPython
```

## Numpy check:
```python
/path_to/nogil/nogil_build/lib/python3.9/site-packages/IPython/core/history.py:226: UserWarning: IPython History requires SQLite, your history will not be saved
  warn("IPython History requires SQLite, your history will not be saved")
Python 3.9.0a4+ (heads/nogil:b0ee2c4740, Oct 25 2021, 16:13:02)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np
In [2]: a = np.arange(0, 1000, 0.1)

In [3]: a
Out[3]:
array([0.000e+00, 1.000e-01, 2.000e-01, ..., 9.997e+02, 9.998e+02,
       9.999e+02])

In [4]: a += 1

In [5]: a
Out[5]:
array([1.0000e+00, 1.1000e+00, 1.2000e+00, ..., 1.0007e+03, 1.0008e+03,
       1.0009e+03])
```

So I think this issue could be closed (and maybe add more precise description of how to build python)

**Comment by colesbury** [comment]
@smontanaro can you share the commands you used to install nogil Python? Is `PYTHONHOME` or `PYTHONPATH` set? (`env | grep PYTHON`). It looks like `pip` is using some details from your system installed Python.

**Comment by Red-Eyed** [comment]
> @smontanaro can you share the commands you used to install nogil Python? Is `PYTHONHOME` or `PYTHONPATH` set? (`env | grep PYTHON`). It looks like `pip` is using some details from your system installed Python.

Yeah, that's might be a problem as well

to unset all `PYTHON*` variables in bash
```bash
unset ${!PYTHON@}
```

So that cmdline could be executed before trying to build python

**Comment by smontanaro** [comment]
Sorry for the noise. I routinely run with an active Conda environment (even when working in my Python repo). It's never given me problems before, though I will admit not to have ever used a PyPI index which injects a nonstandard location into the search path, nor have I ever installed prebuilt wheels (as far as I know). Once I deactivated my Conda environment and zapped a couple CONDA_* environment variables (which might not have strictly been necessary), I was able to reproduce @Red-Eyed's build/install/smoketest. Other differences from my normal M.O.:

* I generally always operate from my build directory without installing anything
* I'd not used the --with-ensurepip arg to configure before, simply running `./python -E -m ensurepip` to make pip available on those rare occasions where I needed something not in the stdlib.

I imagine there was crosstalk between my Conda environment and the nogil pip. I generally don't use `~/.local/lib/pythonX.Y/site-packages/` (since I use Conda). I can just delete that directory and start from scratch.

**Comment by smontanaro** [comment]
Oh, and needing to cooperate with other developers is a bit far in the past for me. :-)

**Comment by Red-Eyed** [comment]
> Sorry for the noise. I routinely run with an active Conda environment (even when working in my Python repo). It's never given me problems before, though I will admit not to have ever used a PyPI index which injects a nonstandard location into the search path, nor have I ever installed prebuilt wheels (as far as I know). Once I deactivated my Conda environment and zapped a couple CONDA_* environment variables (which might not have strictly been necessary), I was able to reproduce @Red-Eyed's build/install/smoketest. Other differences from my normal M.O.:
> 
> * I generally always operate from my build directory without installing anything
> * I'd not used the --with-ensurepip arg to configure before, simply running `./python -E -m ensurepip` to make pip available on those rare occasions where I needed something not in the stdlib.
> 
> I imagine there was crosstalk between my Conda environment and the nogil pip. I generally don't use `~/.local/lib/pythonX.Y/site-packages/` (since I use Conda). I can just delete that directory and start from scratch.

To avoid delation, you can also run python interpreter with [-E](https://docs.python.org/3/using/cmdline.html#cmdoption-E) and [-s](https://docs.python.org/3/using/cmdline.html#cmdoption-s) options.
e.g.: `./bin/python3 -E -s -m IPython`
