### ISSUE TITLE
Is it possible to trick Numpy as having GIL?

### ISSUE THREAD

**Issue by datdinhquoc** [colesbury/nogil#27]
Python nogil builds OK, with Pip. But Numpy won't compile (I have to compile coz pip can't find a suitable Numpy prebuilt).

Numpy build error:
```
numpy/core/src/multiarray/shape.c: In function ‘PyArray_Resize’:
numpy/core/include/numpy/ndarrayobject.h:102:51: error: ‘PyObject’ {aka ‘struct _object’} has no member named ‘ob_refcnt’
    102 | #define PyArray_REFCOUNT(obj) (((PyObject *)(obj))->ob_refcnt)
        |                                                   ^~
numpy/core/src/multiarray/shape.c:108:22: note: in expansion of macro ‘PyArray_REFCOUNT’
    108 |             refcnt = PyArray_REFCOUNT(self);
```

I guess the Python nogil source code has removed that variable `ob_refcnt`, and Numpy without doubts won't compile. **Is it possible to trick that Numpy about the variables about GIL it needs?**

**Comment by erlend-aasland** [comment]
Changing it to use [Py_REFCNT](https://docs.python.org/3/c-api/structures.html#c.Py_REFCNT) should work:

https://github.com/colesbury/nogil/blob/b0ee2c47400b4692c6745a3db3d546e1bc3a1440/Include/object.h#L138

https://github.com/colesbury/nogil/blob/b0ee2c47400b4692c6745a3db3d546e1bc3a1440/Include/object.h#L794-L811

**Comment by datdinhquoc** [comment]
@erlend-aasland oh man, tks, this works! numpy compiled perfectly:

change:
```
108 |             refcnt = PyArray_REFCOUNT(self);
```

to:
```
108 |             refcnt = Py_REFCNT(self);
```

**Comment by colesbury** [comment]
There are additional changes need to run NumPy without the GIL. I'm tracking them in my fork. See https://github.com/colesbury/numpy/commits/v1.19.4-nogil

You can either check out the repository and build it or use the following command:

```
pip3 install git+https://github.com/colesbury/numpy.git@v1.19.4-nogil
```

Or to use multiple cores to build use something like:

```
NPY_NUM_BUILD_JOBS=8 pip3 install git+https://github.com/colesbury/numpy.git@v1.19.4-nogil
```
