### ISSUE TITLE
Make this fork available in pyenv

### ISSUE THREAD

**Issue by thedrow** [colesbury/nogil#33]
This fork would be much easier to test if it was available for installation using pyenv.

Some people don't know how make or autotools work but they do know Python well enough to be familiar with pyenv.
Let's make it easier for them to test the project.

**Comment by colesbury** [comment]
That's a good idea. I'll look into it.

**Comment by Riatre** [comment]
Turns out this is easy, drop a file `nogil-3.9.9` under https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build:

```
#require_gcc
prefer_openssl11
export PYTHON_BUILD_CONFIGURE_WITH_OPENSSL=1
install_package "openssl-1.1.1l" "https://www.openssl.org/source/openssl-1.1.1l.tar.gz#0b7a3e5e59c34827fe0c3a74b7ec8baef302b98fa80088d7f9153aa16fa76bd1" mac_openssl --if has_broken_mac_openssl
install_package "readline-8.1" "https://ftpmirror.gnu.org/readline/readline-8.1.tar.gz#f8ceb4ee131e3232226a17f51b164afc46cd0b9e6cef344be87c65962cb82b02" mac_readline --if has_broken_mac_readline
install_package "Python-3.9.9-nogil" "https://github.com/colesbury/nogil/archive/9ba739f8155464e5c8482ab726d0c66ea6499c0f.tar.gz#c2b87608109b79cb3872f0771b4d21b786431245561ce1d024415a12cb34e7b7" standard verify_py39 copy_python_gdb ensurepip
```

`pyenv install nogil-3.9.9` works then. I would like to try to get it incorporated upstream, but as the source archive is pinned to a SHA256 digest, do we have a release .tar.gz or release tag which could be used here?

**Comment by manueldeprada** [comment]
so nice!! @colesbury Please add a tag to the Git repo so we can have an stable .tar.gz🙏🙏 for example, each time you make a docker release.

**Comment by colesbury** [comment]
This is merged into `pyenv`. Thanks everyone for pushing on this and @Riatre for the help with the definition file.

On Linux, you can run:

```
pyenv update
pyenv install nogil-3.9.10
```

On macOS with homebrew, you'll have to wait for the next release or use the more complicated steps described in the wiki: https://github.com/colesbury/nogil/wiki/Install-nogil-with-pyenv-on-macOS.

I'll update the README with instructions on installing with pyenv.
