### ISSUE TITLE
numpy.array crash in thread

### ISSUE THREAD

**Issue by shikui08** [colesbury/nogil#41]
Executing np.array in threaded function and the program crash.
Versions: 
nogil : default branch from https://github.com/colesbury/nogil.git
numpy: v1.22.0-nogil from https://github.com/colesbury/numpy.git

Test program:

<pre>

import sys
import numpy as np
from concurrent.futures import ThreadPoolExecutor

print(f"nogil={getattr(sys.flags, 'nogil', False)}")

def fib(n):
    b = np.array(((4,4,4,4),(4,4,4,4),(4,4,4,4),(4,4,4,4)), dtype=np.float64)
    if n < 2: return 1
    return fib(n-1) + fib(n-2)

threads = 8
if len(sys.argv) > 1:
    threads = int(sys.argv[1])

with ThreadPoolExecutor(max_workers=threads) as executor:
    for _ in range(threads):

     executor.submit(lambda: print(fib(18)))

</pre>

**Comment by colesbury** [comment]
Hi @shikui08, thanks for the bug report. I'm able to reproduce this issue with NumPy v1.22.0-nogil. It's not present in in NumPy v1.19.3-nogil. I'll have a fix soon.

**Comment by colesbury** [comment]
I've pushed fixes to:

- https://github.com/colesbury/numpy/tree/v1.22.0-nogil
- https://github.com/colesbury/numpy/tree/v1.22.3-nogil

I've also uploaded a wheel with the fix for NumPy 1.22.3 for Linux/x86_64.

Please let me know if this fixes the problem for you or if you run into additional issues.

**Comment by shikui08** [comment]
Thanks for your great work. Currently using multiprocessing. Multithreading without GIL sounds great and indeed comes as a first thought. Definitely will give it a try if  performance becomes bottleneck. 


> I've pushed fixes to:
> 
>     * https://github.com/colesbury/numpy/tree/v1.22.0-nogil
> 
>     * https://github.com/colesbury/numpy/tree/v1.22.3-nogil
> 
> 
> I've also uploaded a wheel with the fix for NumPy 1.22.3 for Linux/x86_64.
> 
> Please let me know if this fixes the problem for you or if you run into additional issues.
