### ISSUE TITLE
Cannot compile nogil with OSX Big Sur (Intel)

### ISSUE THREAD

**Issue by thedrow** [colesbury/nogil#45]
See [build log](https://gist.github.com/thedrow/6a521374b392bcaffc9a54c0063670ea) for details.

**Comment by colesbury** [comment]
I've made fixes for OSX on the [nogil-3.9.10](https://github.com/colesbury/nogil/tree/nogil-3.9.10) branch. I'm planning to promote this to the primary branch, but I still need to do some additional clean up and testing.

**Comment by colesbury** [comment]
This is fixed now in the main `nogil` branch. I've forced pushed to that branch, so you'll need to either re-clone the repository or, if you want to keep an existing checkout, run:

```
git fetch origin
git reset --hard origin/nogil
```

in order to get the changes in the nogil branch.
