### ISSUE TITLE
Celery test suite results

### ISSUE THREAD

**Issue by thedrow** [colesbury/nogil#49]
https://gist.github.com/thedrow/caa5ff0598a3a06456f9742187307b2d

There are a number of failing tests which don't fail in CPython or PyPy.

@colesbury Could you please review the results?

**Comment by colesbury** [comment]
@thedrow those look like test results from CPython 3.10.3, not this fork

```
platform darwin -- Python 3.10.3, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/okatz6/.pyenv/versions/3.10.3/bin/python3.10
```

**Comment by colesbury** [comment]
@thedrow I've run the tests locally and the only test that failed was `t/unit/concurrency/test_prefork.py::test_AsynPool::test_gen_not_started`. That should be fixed by this PR:

https://github.com/celery/celery/pull/7476
