### ISSUE TITLE
Jump too big RuntimeError raised while importing some commonly used libraries

### ISSUE THREAD

**Issue by FasterSpeeding** [colesbury/nogil#5]
Importing some commonly used libraries (youtube==2021.6.6 and beautifulsoup4==4.10.0 are the two examples I can reproduce this behaviour on myself) leads to the following runtime error being raised by compile2.c:

```py
Traceback (most recent call last):
  File "//main.py", line 1, in <module>
    import bs4
  File "/usr/local/lib/python3.9/site-packages/bs4/__init__.py", line 38, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python3.9/site-packages/bs4/builder/__init__.py", line 7, in <module>
    from bs4.element import (
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 19, in <module>
    from bs4.formatter import (
  File "/usr/local/lib/python3.9/site-packages/bs4/formatter.py", line 1, in <module>
    from bs4.dammit import EntitySubstitution
RuntimeError: jump too big: 41352
```

This leads to compatibility issues as this error isn't seen on the reference Cpython 3.9.0.a3 release (since compile2.c is unique to this fork)
 
For reference I'm running this on the latest tag of https://hub.docker.com/r/colesbury/python-nogil with the following files:

#main.py
```py
import bs4
#import youtube_dl
```

#Dockerfile
```docker
FROM colesbury/python-nogil

COPY ./main.py ./main.py

RUN python -m pip install --upgrade pip wheel
RUN python -m pip install youtube_dl==2021.6.6
RUN python -m pip install beautifulsoup4==4.10.0

ENTRYPOINT python main.py
```

All I can really contribute myself right now is a link to the offending line https://github.com/colesbury/nogil/blob/84c1b14af40d406a789d4229f67546b069cc4a25/Python/compile2.c#L1125

**Comment by colesbury** [comment]
Thanks for the detailed bug report. I've fixed the issue on GitHub. I'm working on re-building the Docker image now

**Comment by colesbury** [comment]
The docker image is updated now. (Make sure to run `docker pull colesbury/python-nogil`).
