### ISSUE TITLE
nogil fails to build under pyperformance --compile

### ISSUE THREAD

**Issue by markshannon** [colesbury/nogil#52]
I get the error:
```
Assembler messages:
Fatal error: can't create Objects/mimalloc/alloc-aligned.o: No such file or directory
```
It appears `pyperformance` is building out of tree, and `Objects/mimalloc/` doesn't exist in the build directory.
Manually creating the `.../bench_tmpdir/build/Objects/mimalloc/` during the build allowed the build to complete.

Maybe add a `Objects/mimalloc` target to Makefile.pre.in ?

**Comment by colesbury** [comment]
Fixed in https://github.com/colesbury/nogil/commit/df2ffbdfa3a26eb932dd483b7aea030e49c6a3c8

(The directory is now created during configure to match how `Parser/pegen` is created)
