### ISSUE TITLE
"gc_get_refs(gc): -1" debug prints on stdout

### ISSUE THREAD

**Issue by ogrisel** [colesbury/nogil#53]
This is making some scikit-learn tests fail, e.g. in `sklearn/experimental/tests/test_enable_iterative_imputer.py` the `test_imports_strategies` test fails because it expects nothing on stdout and stderr but gets:

```
gc_get_refs(gc): -1
gc_get_refs(gc): -1
gc_get_refs(gc): -1
```

from https://github.com/colesbury/nogil/blob/nogil/Modules/gcmodule.c#L757

Maybe this is revealing a real bug?

**Comment by colesbury** [comment]
Yes, I think it's a real bug. I'll look into it.

**Comment by colesbury** [comment]
This should be fixed now in https://github.com/colesbury/nogil/commit/87c61c34a1e69b802b1a2711e67c77436896d51d

**Comment by ogrisel** [comment]
I confirm that this fixes the failing test.

All scikit-learn tests now pass! :champagne:
