### ISSUE TITLE
Segfault when importing within ptpython

### ISSUE THREAD

**Issue by john9631** [colesbury/nogil#6]
Built with and without enable optimisations on

```
System:
  Host: home Kernel: 5.10.0-9-amd64 x86_64 bits: 64 Desktop: dwm 6.2
  Distro: Debian GNU/Linux 11 (bullseye)
CPU:
  Info: 6-Core AMD Ryzen 5 3600 [MT MCP] speed: 2198 MHz
  min/max: 2200/3600 MHz
```

`./pip3 install --upgrade ptpython`

`./python3 -m ptpython`

Imports cause seg faults (not true in python or ipython shells):

```
>>> import sys; print(sys.version)
3.9.0a4+ (heads/nogil:84c1b14af4, Oct 17 2021, 07:52:16) 
[GCC 10.2.1 20210110]
Segmentation fault
```

Undefined commands like ls without bang also cause a seg fault.

Interesting work thank you.  I'll try it out some more later with the backtrader module.

**Comment by colesbury** [comment]
Thanks for the bug report. This should be fixed now. Please let me know if you run into any other issues.

**Comment by john9631** [comment]
Fixed thanks.  Will do.
