### ISSUE TITLE
Unexpected __code__.__hash__() collision for lambda functions

### ISSUE THREAD

**Issue by ogrisel** [colesbury/nogil#62]
On the `nogil` branch we have:

```python
>>> (lambda x: x).__code__.__hash__() == (lambda x: x + 1).__code__.__hash__()
True
```

While on regular CPython it evaluates to `False`.

Not sure if it's a bug or not but this is making `test_memory_warning_lambda_collisions` fail on the joblib test suite:

https://github.com/joblib/joblib/blob/1fdf3086674d7b1be27688e8c7aebd3159d89997/joblib/test/test_memory.py#L303

**Comment by colesbury** [comment]
I've improved the hash function in f3b6e462dcee0277089a49232c3a261796f8f859 to fix the code snippet

**Comment by ogrisel** [comment]
I confirm this fixed the problem.
