### ISSUE TITLE
Warning at numpy import: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__

### ISSUE THREAD

**Issue by lesteve** [colesbury/nogil#63]
```
python -W error -c 'import numpy'
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/numpy/__init__.py", line 155, in <module>
    from . import random
  File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 19, in init numpy.random.mtrand
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

Note that the warning is not visible when doing `python -c 'import numpy'` probably because the default warning filters filters it out.

I guess this is not a major blocker at all, but some projects turns warnings into errors (except for a few whitelisted warnings) in their pytest configuration e.g. distributed: https://github.com/dask/distributed/blob/8035d36de48f81e7fac5fb7fe78f8436ea2e40ac/setup.cfg#L43-L46. 

Googling a bit I found an old issue in Cython that has been resolved
https://github.com/cython/cython/issues/1720, this is probably not the same issue, but this may have some useful information.

**Comment by colesbury** [comment]
Thanks for the bug report. I'll investigate this.

**Comment by colesbury** [comment]
This is now fixed by enabling PEP 489 multi-phase init in Cython for nogil: https://github.com/colesbury/cython/commit/6921a8ab857d8491e73b53d066a6c72d172471dd

I've rebuilt and re-uploaded NumPy. I still need to re-build scipy and potentially some other packages.

**Comment by colesbury** [comment]
I've rebuilt and uploaded SciPy and scikit-learn as well. Let me know if you run into these ImportWarnings in any other projects and I'll rebuild those a swell.

**Comment by lesteve** [comment]
Thanks a lot, closing this one!
