### ISSUE TITLE
Error when using nogil with pybind

### ISSUE THREAD

**Issue by hengyuan-hu** [colesbury/nogil#65]
Hi, I am encountering some segmentation fault when using this interpreter to call some C++ code with pybind11. I tried to create a minimal example here. https://github.com/hengyuan-hu/nogil-pybind/tree/main

I know that some changes need to be made in order for pybind to work so the pybind11 in the above repo uses the modified files extracted from the customized whl file (see the readme in the repo). I am not sure whether this is the proper way to do it.

The error seems to appear when I create and garbage collect (deallocate) a bunch of pybinded objects in parallel loops across threads. If I just pybind a function, it works fine.

Please let me know if more details are needed. Thanks!

**Comment by colesbury** [comment]
Hi @hengyuan-hu, the pybind11 whl file was missing some fixes from the git repo. Sorry about that. I've updated it, so if you re-download the wheel you'll get the fixes.

The changes are also available in https://github.com/colesbury/pybind11 (the v2.6.2-nogil branch), if that's easier than downloading and extracting the wheel.

**Comment by colesbury** [comment]
Here's a modified version of your example that installs pybind11 via pip.

https://github.com/colesbury/nogil-pybind

The advantage is that you don't need to pull in the specific patched pybind11 into your project. (So you can build it with either "nogil" Python or upstream Python and it'll use the correct pybind11 version).
