### ISSUE TITLE
unable to install numpy==1.18.5 with nogil

### ISSUE THREAD

**Issue by zigzagcai** [colesbury/nogil#71]
I tried to build nogil-compatible tensorflow2.2.0 from source, but bazel reported the requirements that numpy<1.19 and seems that nogil package repository not compatible with numpy==1.18.5.
Error Msg:
`pip install numpy==1.18.5
Looking in indexes: https://d1yxz45j0ypngg.cloudfront.net/, https://pypi.org/simple
ERROR: Could not find a version that satisfies the requirement numpy==1.18.5 (from versions: 1.19.3, 1.19.4, 1.22.3)
ERROR: No matching distribution found for numpy==1.18.5`

Do you have any ideas about how to install specific version of numpy with nogil. Thanks!

**Comment by zigzagcai** [comment]
Updated:

I have made some modifications to [numpy-v1.18.5-nogil](https://github.com/zigzagcai/numpy/tree/v1.18.5-nogil) and make it compatible with nogil.

**Comment by zigzagcai** [comment]
This issue has been resolved.

Added link for commit:
https://github.com/colesbury/numpy/commit/0d6ef2770268711ee6417792ba0da35fcb264bf5

**Comment by colesbury** [comment]
Awesome - I'll copy your branch into my fork and publish a wheel for 1.18.5 to the alternate package index in case other people want to use it as well.

**Comment by colesbury** [comment]
I've added NumPy 1.18.5 wheel based on your branch.
