### ISSUE TITLE
Inability to compile on Windows.

### ISSUE THREAD

**Issue by ChefJodlak** [colesbury/nogil#74]
Hello, I am trying to compile nogil on Windows which is endping with LNK2019 and LNK1120 errors.
I am using VisualStudio Code 2017.
![errors](https://user-images.githubusercontent.com/45046499/180662319-07902556-3608-49e2-9827-ee8e68601678.png)

Do you know what might be a reason?

**Comment by colesbury** [comment]
Hi @ChefJodlak - I'm able to reproduce the issue. I'll have a fix later today.

For what it's worth, you'll probably have a better experience on Linux (including on [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)/WSL2). There are a lot more compatible binary wheels (like NumPy, SciPy, etc.) built for Linux than for Windows.

**Comment by ChefJodlak** [comment]
We want to test a nogil for a Windows application that automates actions in ecommerce systems by sending requests and performing simple logic operations. We don't need specific libraries like numpy.

At large scale, we feel that GIL is the bottleneck.

**Comment by colesbury** [comment]
This is fixed now in https://github.com/colesbury/nogil/commit/55d895ff819c75cb0b1694ecce5c23c50a46d568

Make sure to compile for 64-bit/x64. I don't think it currently works in 32-bit mode.

Please let me know if you run into any more issues.

**Comment by colesbury** [comment]
I've also built a Windows installer, in-case that's easier to use:

https://github.com/colesbury/nogil/releases/download/v3.9.10-nogil/python-3.9.10-amd64.exe

**Comment by ChefJodlak** [comment]
[EDIT] I've managed to bypass issue with Pillow using:
`python-nogil -m pip install Pillow --global-option="build_ext" --global-option="--disable-zlib" --global-option="--disable-jpeg"`

I found out that we are not able to use `.whl` made for **cp39-cp39-win_amd64**.  I understand it is a standard issue for custom CPython?

**Comment by colesbury** [comment]
Yes, those wheels are not compatible. That's what I meant by "there are a lot more compatible binary wheels for Linux than for Windows." I've built compatible wheels for things like Pillow on Linux, but not on Windows.

**Comment by stonebig** [comment]
Hello,

Are you going to build  more 'nogil' wheels for windows ? pillow and kiwisolver for example.

**Comment by thedrow** [comment]
> Hello,
> 
> Are you going to build more 'nogil' wheels for windows ? pillow and kiwisolver for example.

If there's something specific you need and the maintainer is willing to provide, I think it's better to open a separate issue rather than piggybacking this one.

**Comment by colesbury** [comment]
@stonebig, yes I will be building more Windows wheels in the next few days. I'll make sure to include pillow and kiwisolver. If there are additional Windows wheels you'd like, please open a new issue as @thedrow suggests. It's harder for me to keep track of requests on older closed issues.
