### ISSUE TITLE
 import  xx.pyd  bug

### ISSUE THREAD

**Issue by houshijie-2020** [colesbury/nogil#81]
**1 embed cpython into demo.exe**
**demo.cpp**
`
#include <iostream>
#include <stdio.h>
#include <string>
#include "Python.h"
using namespace std;
void Python_run_file(const string& file_name)
{
    FILE* file;
    file = fopen(  file_name.c_str(), "r");
    PyRun_SimpleFile(file, file_name.c_str());
    fclose(file);
}

int main()
{
    Py_Initialize();   
    Python_run_file("test_mnn.py");
    if (Py_FinalizeEx() < 0) {
        cout << "Py_FinalizeEx err" << endl;
        exit(120);
    }
    return 0;
}

`

**2 the test_mnn.py is in  D:\Users\8000\Documents\GitHub\nogil\PCbuild\amd64, its code is as below**
`
import  pymnn 
`
**3 the pymnn.pyd and mnn.dll（used by  pymnn.pyd ）（mnn.pyd use mnn.dll） file are in  D:\Users\8000\Documents\GitHub\nogil\PCbuild\amd64**；then i run demo.exe  in path: D:\Users\8000\Documents\GitHub\nogil\PCbuild\amd64
the  pymnn.pyd and mnn.dll are test sucessfully with the orginpython project(3.9) ,but the nogil project failed;

**Comment by houshijie-2020** [comment]
i load the mnn.pyd and mnn.dll sucessfully with cpyton3.9 branch ；
but failed with the nogil project

**Comment by houshijie-2020** [comment]
![image](https://user-images.githubusercontent.com/65584476/187220455-c8859d3e-414c-473c-b0f9-c24da44a0ed4.png)
this is core stack
it fails at  this line:   m = p0();

**Comment by houshijie-2020** [comment]
0x00007FFCED088914 (pymnn.cp39-win_amd64.pyd)处(位于 Sdk3.0.exe 中)引发的异常: 0xC0000005: 读取位置 0x00000000000000AC 时发生访问冲突。

**Comment by colesbury** [comment]
Sorry - there is not enough information in this bug report to be take any action.

**Comment by houshijie-2020** [comment]
> Sorry - there is not enough information in this bug report to be take any action.

what else is needed ? i can send you the pyd and dll files
