### ISSUE TITLE
install  numpy fails 

### ISSUE THREAD

**Issue by houshijie-2020** [colesbury/nogil#82]
i build nogil ,and use nigil as defaut python;
when i install numpy with pip,it report a error:
![image](https://user-images.githubusercontent.com/65584476/187617093-3b590b98-7cb4-47c7-8984-06b60b18303d.png)

**Comment by ghost** [comment]
Try running these two commands.
```
python -m pip install --upgrade pip --user
python -m pip install numpy==1.23.2 --user
```

**Comment by houshijie-2020** [comment]
> Try running these two commands.
> 
> ```
> python -m pip install --upgrade pip --user
> python -m pip install numpy==1.23.2 --user
> ```

**dont works
the error happened when compile numpy/core/shape.cc:**
 
       shape.c
      numpy\core\src\npymath\npy_math_internal.h.src(897): warning C4244: “return”: 从“unsigned short”转换到“uint8_t”，可能丢失数据
      numpy\core\src\npymath\npy_math_internal.h.src(903): warning C4244: “return”: 从“unsigned __int64”转换到“uint8_t”，可能丢失数据
      numpy\core\src\multiarray\shape.c(108): error C2039: "ob_refcnt": 不是 "_object" 的成员
      D:\Users\80000000\Documents\GitHub\nogil-nogil\include\object.h(112): note: 参见“_object”的声明
      numpy\core\src\multiarray\shape.c(226): warning C4244: “函数”: 从“npy_intp”转换到“int”，可能丢失数据
      numpy\core\src\multiarray\shape.c(695): warning C4244: “初始化”: 从“npy_intp”转换到“int”，可能丢失数据
      numpy\core\src\multiarray\shape.c(929): warning C4244: “函数”: 从“npy_intp”转换到“int”，可能丢失数据
      numpy\core\src\multiarray\shape.c(936): warning C4244: “函数”: 从“npy_intp”转换到“int”，可能丢失数据
      error: Command "D:\SoftWare\vs2019\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild\src.win-amd64-3.9\numpy\core\src\multiarray -Ibuild\src.win-amd64-3.9\numpy\core\src\common -Ibuild\src.win-amd64-3.9\numpy\core\src\umath -Inumpy\core\include -Ibuild\src.win-amd64-3.9\numpy\core\include/numpy -Ibuild\src.win-amd64-3.9\numpy\distutils\include -Ibuild\src.win-amd64-3.9\numpy\core\src\npysort -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -Inumpy\core\src\_simd -ID:\Users\80000000\Documents\GitHub\nogil-nogil\include -ID:\Users\80000000\Documents\GitHub\nogil-nogil\PC -ID:\Users\80000000\Documents\GitHub\nogil-nogil\PC -Ibuild\src.win-amd64-3.9\numpy\core\src\common -Ibuild\src.win-amd64-3.9\numpy\core\src\npymath -ID:\SoftWare\vs2019\VC\Tools\MSVC\14.29.30133\ATLMFC\include -ID:\SoftWare\vs2019\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\cppwinrt /Tcnumpy\core\src\multiarray\shape.c /Fobuild\temp.win-amd64-3.9\Release\numpy\core\src\multiarray\shape.obj /Zm1000" failed with exit status 2
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   :
                    :
        SSE41       : SSE SSE2 SSE3 SSSE3
        Flags       :
        Extra checks: none
        Detect      : SSE SSE2 SSE3 SSSE3 SSE41
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_unary_fp.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_arithmetic.dispatch.c
                    :
        SSE42       : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT
        Flags       :
        Extra checks: none
        Detect      : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42
                    : build\src.win-amd64-3.9\numpy\core\src\multiarray\argfunc.dispatch.c
                    :
        AVX2        : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3
        Flags       : /arch:AVX2
        Extra checks: none
        Detect      : AVX F16C FMA3 AVX2
                    : build\src.win-amd64-3.9\numpy\core\src\multiarray\argfunc.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_arithm_fp.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_arithmetic.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_minmax.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_trigonometric.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_exponent_log.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_hyperbolic.dispatch.c
                    :
        AVX512F     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512CD AVX512_SKX
        Flags       : /arch:AVX512
        Extra checks: AVX512F_REDUCE
        Detect      : AVX512_SKX
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_arithm_fp.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_trigonometric.dispatch.c
                    :
        AVX512_SKX  : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD
        Flags       : /arch:AVX512
        Extra checks: AVX512BW_MASK AVX512DQ_MASK
        Detect      : AVX512_SKX
                    : numpy\core\src\npysort\x86-qsort.dispatch.cpp
                    : build\src.win-amd64-3.9\numpy\core\src\multiarray\argfunc.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_arithmetic.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_minmax.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_umath_fp.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_exponent_log.dispatch.c
                    : build\src.win-amd64-3.9\numpy\core\src\umath\loops_hyperbolic.dispatch.c
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> D:\Users\80000000\Documents\GitHub\nogil-nogil\numpy-1.23.2\build\temp.win-amd64-3.9\Release\ccompiler_opt_cache_ext.py
      INFO:
      ########### CLIB COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> D:\Users\80000000\Documents\GitHub\nogil-nogil\numpy-1.23.2\build\temp.win-amd64-3.9\ccompiler_opt_cache_clib.py
      [end of output]

**Comment by houshijie-2020** [comment]
> Try running these two commands.
> 
> ```
> python -m pip install --upgrade pip --user
> python -m pip install numpy==1.23.2 --user
> ```

this error only happens when i use compiled nogil as default python interpreter;

**Comment by colesbury** [comment]
I've provided pre-built binary wheels for NumPy on Linux and macOS, but not for Windows. You will have to build extensions yourself for nogil on Windows. The experience is much better on Linux, so I recommend it, if that is an option (including WSL2).

For NumPy, you will have to build from this fork and branch https://github.com/colesbury/numpy/tree/v1.22.3-nogil, which has changes required for nogil Python.

**Comment by houshijie-2020** [comment]
> I've provided pre-built binary wheels for NumPy on Linux and macOS, but not for Windows. You will have to build extensions yourself for nogil on Windows. The experience is much better on Linux, so I recommend it, if that is an option (including WSL2).
> 
> For NumPy, you will have to build from this fork and branch https://github.com/colesbury/numpy/tree/v1.22.3-nogil, which has changes required for nogil Python.

is  opencv-python compatible ?

**Comment by houshijie-2020** [comment]
Traceback (most recent call last):
    File "/usr/local/python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/local/python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-roxbqj51/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-roxbqj51/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-roxbqj51/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-roxbqj51/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 461, in <module>
      setup_package()
    File "setup.py", line 453, in setup_package
      setup(**metadata)
    File "/home/service/var/data/houkun/numpy/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "setup.py", line 131, in configuration
      config.add_subpackage('numpy')
    File "/home/service/var/data/houkun/numpy/numpy/distutils/misc_util.py", line 1054, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/home/service/var/data/houkun/numpy/numpy/distutils/misc_util.py", line 1020, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/home/service/var/data/houkun/numpy/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "numpy/setup.py", line 9, in configuration
      config.add_subpackage('core')
    File "/home/service/var/data/houkun/numpy/numpy/distutils/misc_util.py", line 1054, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/home/service/var/data/houkun/numpy/numpy/distutils/misc_util.py", line 1020, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/home/service/var/data/houkun/numpy/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "numpy/core/setup.py", line 1018, in configuration
      if can_link_svml() and check_svml_submodule(svml_path):
    File "numpy/core/setup.py", line 84, in check_svml_submodule
      raise RuntimeError("Missing `SVML` submodule! Run `git submodule "
  RuntimeError: Missing `SVML` submodule! Run `git submodule update --init` to fix this.



how to fix this?thanks

**Comment by colesbury** [comment]
> is opencv-python compatible ?

Yes, there is a pre-built opencv-python wheel (4.5.3.56) for Linux

**Comment by houshijie-2020** [comment]
> > is opencv-python compatible ?
> 
> Yes, there is a pre-built opencv-python wheel (4.5.3.56) for Linux
is there any git project fot this versin?

**Comment by houshijie-2020** [comment]
pillow  is not compatible ？

is the compatibility problem serious  for nogil-cpython？

**Comment by colesbury** [comment]
There's now a pre-built NumPy wheel for nogil Python on Windows. For reference, here's a table of pre-built wheels:

https://github.com/colesbury/nogil/wiki/Supported-C-API-Extensions
