### ISSUE TITLE
Is there some interest to have the `nogil/python` docker image updated on each commit?

### ISSUE THREAD

**Issue by lesteve** [colesbury/nogil#84]
We are currently building nogil in scikit-learn CI and testing against it.

It could potentially slightly simplify our setup and also reduce our CI build time to be able to use the `colesbury/nogil` docker image. 

It would be nice if the docker image was updated on each commit, which does not seem to be the case right now. The latest update to the docker image is May 18 2022, if I read the [dockerhub page](https://hub.docker.com/r/nogil/python/tags) correctly but there has been some commits since.

Maybe you prefer to push the docker image manually or there are some other complications that I missed ...

It does not seem like it would be that much work to set-up and I could devote some time if that can help making it happen!

**Comment by lesteve** [comment]
Of course the low-tech alternative is to use the `nogil/python` docker image and accept that this is not always up-to-date. Maybe that is good enough for our purposes.

**Comment by colesbury** [comment]
Hi @lesteve, a GitHub actions workflow that automatically updates the Docker image would be great. I'd be happy to accept a PR that sets that up, if you have some time to look into it.
