### ISSUE TITLE
nogil does not optimize mac pro M1 chip(arm64)

### ISSUE THREAD

**Issue by Roxas** [colesbury/nogil#86]
When I try to use nogil with your fab.py on my mac pro M1，I found nogil could not make use m1 8 cores.  And it seems like it dose not support arm chip as good as x86. when I use 1 thread run fab.py with nogil, it use 8 seconds, but I use 1 thread run fab.py with CPython, it just use 1 seconds. I also run this fab.py script on my intel x86 server,  its performance is so surprised as your tips.

**Comment by colesbury** [comment]
How did you build/install it? I have an M1 mac and it scales well and runs quickly.

**Comment by colesbury** [comment]
I'm closing this issue because it needs more information. Feel free to re-open it with additional information.

**Comment by Roxas** [comment]
> How did you build/install it? I have an M1 mac and it scales well and runs quickly.

I run fab.py by  nogil/python docker container. this is my test env docker-compose.yml:
`version: "3"
services:
  nogil:
    image: nogil/python:latest
    #image: python:3.10.1-slim-buster
    restart: always
    volumes:
    - ./src:/src`

there is test.py in src dir: the contente is same fab.py
