### ISSUE TITLE
Package request - Pillow-9.3.0

### ISSUE THREAD

**Issue by Cheukting** [colesbury/nogil#87]
I ran into an installation error when installing Pillow.

```
Collecting pillow>=8.3.2
  Downloading Pillow-9.3.0.tar.gz (50.4 MB)
     |████████████████████████████████| 50.4 MB 3.1 MB/s            
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pillow, since package 'wheel' is not installed.
Installing collected packages: pillow, imageio
    Running setup.py install for pillow ... error
    ERROR: Command errored out with exit status 1:

  ...
  
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
```
 
I guess that there's no pre-build available. Before I tried to build it myself. I wonder is it possible to have the pre-build available?

The processor on my mac is 3.1 GHz Dual-Core Intel Core i7 so yes it's an x86-64 (Intel) mac.

Thank you very much.

**Comment by colesbury** [comment]
Hi @Cheukting, I'll look into building a version of Pillow for nogil on macOS.

**Comment by colesbury** [comment]
I've uploaded a Pillow 9.3.0 wheel for nogil Python on Intel macOS. `pip install pillow` should now use it.

Please let me know if you run into any issues.

**Comment by Cheukting** [comment]
Thank you, really appreciate it. It works!

**Comment by Cheukting** [comment]
@colesbury sorry, I have upgraded to an M2 MacBook air - with MacOS 13.0. Do you mind providing a compatible Pillow wheel for it? (latest version is Pillow-9.5.0) Thank you so much

**Comment by colesbury** [comment]
@Cheukting I added Pillow 9.5.0 for macOS arm64. (For some reason I'm having trouble building the macOS x86-64 package)
