### ISSUE TITLE
nogil pytorch pip install not support 

### ISSUE THREAD

**Issue by sdli1995** [colesbury/nogil#88]
I build nogil from source and try install pytorch use pip like this command:
pip install torch --index-url https://download.pytorch.org/whl/cu116
or 
pip install ../lib/nogil/torch-1.9.1+cu111-cp39-cp39-linux_x86_64.whl
and rlst is  "ERROR: Could not find a version that satisfies the requirement torch (from versions: none) or ERROR: torch-1.9.1+cu111-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform."

**Comment by oraluben** [comment]
The nogil cannot use some packages built for CPython. You can use just `pip install torch` to install a modified torch:https://github.com/colesbury/nogil#packages

**Comment by colesbury** [comment]
What @oraluben said is correct.  You can run `pip install torch` to get PyTorch 1.9 with CUDA 11.0 on Linux.

**Comment by sdli1995** [comment]
> What @oraluben said is correct. You can run `pip install torch` to get PyTorch 1.9 with CUDA 11.0 on Linux.



> The nogil cannot use some packages built for CPython. You can use just `pip install torch` to install a modified torch:https://github.com/colesbury/nogil#packages


thanks ! its works
