### ISSUE TITLE
Vscode can not debug nogil 

### ISSUE THREAD

**Issue by sdli1995** [colesbury/nogil#89]
when i use decode debug a file in nogil , the vscode python debug throw an error like this:

```
  File "/home/woker/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_collect_bytecode_info.py", line 7, in <module>
    from opcode import (EXTENDED_ARG, HAVE_ARGUMENT, cmp_op, hascompare, hasconst,
ImportError: cannot import name 'EXTENDED_ARG' from 'opcode' (/home/woker/envs/python-nogil/lib/python3.9/opcode.py)
```

**Comment by colesbury** [comment]
Sorry - I don't think VS code debugging is going to work. It depends on the bytecode format which is changed in the "nogil" Python.

The built-in debugger (pdb) and ipython debugger (ipdb) should work.

**Comment by sdli1995** [comment]
> Sorry - I don't think VS code debugging is going to work. It depends on the bytecode format which is changed in the "nogil" Python.
> 
> The built-in debugger (pdb) and ipython debugger (ipdb) should work.

thanks , i swtch to a normal python environment when i debug
