### ISSUE TITLE
Install with pyenv ubuntu need updation

### ISSUE THREAD

**Issue by bibinvargheset** [colesbury/nogil#92]
First see if you have the curl already installed in your machine using the command:

$ curl --version

If you don't have, install the curl using:

$ sudo apt-get install curl

After that install the pyenv using the command:

$curl https://pyenv.run | bash

And after installation update your bashrc adding the lines:

export PATH="~/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
Finally Reload the bashrc:

$ source ~/.bashrc

**Comment by bibinvargheset** [comment]
if is based on https://akrabat.com/creating-virtual-environments-with-pyenv/ it will be much more acccurate

**Comment by colesbury** [comment]
Thanks, I've updated the wiki with a link to https://github.com/pyenv/pyenv/wiki#suggested-build-environment which has instructions for various Linux distributions.

https://github.com/colesbury/nogil/wiki/Install-nogil-with-pyenv-on-Linux#prerequisites
