### ISSUE TITLE
Can't install rasterio

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [colesbury/nogil#94]
Can't install an important python library for data science rasterio https://rasterio.readthedocs.io/en/latest/installation.html
When I used `pip install rasterio`

**Comment by colesbury** [comment]
Hi @amarouane-ABDELHAK, I'll look into providing a `rasterio` package.

**Comment by amarouane-ABDELHAK** [comment]
Thank you, I appreciate it, please let me know if you have any question.

**Comment by colesbury** [comment]
I've uploaded a pre-built `rasterio` package. You should be able to install it now with `pip install rasterio`.

Please let me know if it works for you or if you run into any issues.

**Comment by amarouane-ABDELHAK** [comment]
It did work thank you for solving this so quickly.
