### ISSUE TITLE
No module named 'sklearn'

### ISSUE THREAD

**Issue by dmitrii-erkin** [colesbury/nogil#97]
Hello,

Despite having sklearn installed:

 => => #   Downloading sklearn-0.0.post1.tar.gz (3.6 kB)                                                                                                       
 => => #   Preparing metadata (setup.py): started                                                                                                              
 => => #   Preparing metadata (setup.py): finished with status 'done'                                                                                          
 => => # Collecting scipy                                                                                                                                      
 => => #   Downloading https://d1yxz45j0ypngg.cloudfront.net/scipy-1.8.1-nogil39-nogil_39b_x86_64_linux_gnu-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (110
 => => # .5 MB)   

 I observe the following issue when I try to run my docker image:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
...
from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'

Could it be because I am using flask?

**Comment by colesbury** [comment]
You should install the "scikit-learn" package, not "sklearn"

**Comment by dmitrii-erkin** [comment]
The issue is fixed, thank you very much.
