### ISSUE TITLE
Compiling torch for MacOS 13 Ventura (M1)

### ISSUE THREAD

**Issue by cdmatters** [colesbury/nogil#99]
I'm trying to compile pytorch v.1.13.0 from source for MacOS (yes CPU only, which simplifies things) and we seem to get _reaaally_ close before you hit something that looks pretty critical. 
<img width="954" alt="Screenshot 2023-01-12 at 20 23 08" src="https://user-images.githubusercontent.com/6815729/212174142-e2a037b8-4c26-4b63-b639-23b32039451f.png">

Is there any chance you happen to have a branch of any modifications you made to pytorch to make it compile for your [custom package index](https://d1yxz45j0ypngg.cloudfront.net/)? Or does this require something a little more involved?

**Comment by cdmatters** [comment]
Ah okay I have found your personal fork of [pytorch with the nogil branch](https://github.com/colesbury/pytorch/tree/v1.9.0-nogil).  I'll try here!

**Comment by colesbury** [comment]
Yeah, that’s the right branch. I haven’t built 1.13 or macOS wheels yet. I’d like to do so, but I won’t have time to look into it until next week.

**Comment by cdmatters** [comment]
I'm actually happy with 1.9.0 but I seem to be setting segfaults building `sleef`

**Comment by cdmatters** [comment]
This is the [error](https://github.com/shibatch/sleef/issues/425) I'm encountering, dubiously no comment since 2021. The comment suggests cross compile should be fine, so maybe wheels will be alright...

**Comment by colesbury** [comment]
I'm looking into this now. I might end up building 1.13 wheels because I'm not sure 1.9.0 supports M1.

**Comment by colesbury** [comment]
I'm still working on building the wheels, but if you are feeling impatient you can try:

```
git clone https://github.com/colesbury/pytorch.git -b v1.13.1-nogil
```

And once you install the prerequisites, build it with:

```
BUILD_FUNCTORCH=0 python setup.py install
```

Functorch doesn't build right now because of changes to the bytecode format and PyCodeObject structure.

**Comment by colesbury** [comment]
I've uploaded PyTorch 1.13.1 wheels for macOS (x86-64 and arm64). Please let me know if you run into any issues.
